// SPDX-FileCopyrightText: 2023 Open Salamander Authors
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// MESSAGES_DISABLE macro - disconnects module from compilation
// MESSAGES_DEBUG macro - outputs file + line number before message + enables messages shown via DMESSAGE_???
// MULTITHREADED_MESSAGES_ENABLE macro - prepares messages for multithreaded applications

#ifndef MESSAGES_DISABLE

#define __RESOURCE_STRING_BUFFER_SIZE 1000
#define __SPRINTF_BUFFER_SIZE 1000
#define __ERROR_BUFFER_SIZE 1000

#ifdef MULTITHREADED_MESSAGES_ENABLE

// ensures current thread access to module functions and data
void EnterMessagesModul();
// call when current thread no longer needs access to module functions and data
void LeaveMessagesModul();

#endif // MULTITHREADED_MESSAGES_ENABLE

/// returns pointer to global buffer, which it fills with string from resources
const char* rsc(int resID);
const WCHAR* rscW(int resID);

/// returns pointer to global buffer, which it fills with string from sprintf
const char* spf(const char* formatString, ...);
const WCHAR* spfW(const WCHAR* formatString, ...);

/// returns pointer to global buffer, which it fills with string from sprintf
const char* spf(int formatStringResID, ...);
const WCHAR* spfW(int formatStringResID, ...);

/// returns pointer to global buffer, which it fills with error description
const char* err(DWORD error);
const WCHAR* errW(DWORD error);

extern const char* __MessagesTitle;
extern const WCHAR* __MessagesTitleW;
extern HWND __MessagesParent;
extern HINSTANCE HInstance; // expected variable with instance handle

/// Setting title of messageboxes generated by MESSAGExx macros. A copy of the string is made.
/// Always sets title for both versions (ANSI + unicode).
void SetMessagesTitle(const char* title);
void SetMessagesTitleW(const WCHAR* title);

/// Setting parent of messageboxes generated by MESSAGExx macros
void SetMessagesParent(HWND parent);

class C__Messages
{
protected:
    C__StringStreamBuf MessagesStringBuf; // string buffer holding messages stream data
    C__TraceStream MessagesStrStream;     // own messages stream

public:
    C__Messages();
#ifdef MULTITHREADED_MESSAGES_ENABLE
    ~C__Messages();
#endif // MULTITHREADED_MESSAGES_ENABLE

    C__TraceStream& OStream()
    {
        return MessagesStrStream;
    }

    int MessageBoxT(const char* lpCaption, // address of title of message box
                    UINT uType);           // style of message box

    int MessageBox(HWND hWnd,             // handle of owner window
                   const char* lpCaption, // address of title of message box
                   UINT uType);           // style of message box
};

class C__MessagesW
{
protected:
    C__StringStreamBufW MessagesStringBuf; // string buffer holding messages stream data
    C__TraceStreamW MessagesStrStream;     // own messages stream

public:
    C__MessagesW();

    C__TraceStreamW& OStream() { return MessagesStrStream; }

    int MessageBoxT(const WCHAR* lpCaption, // address of title of message box
                    UINT uType);            // style of message box

    int MessageBox(HWND hWnd,              // handle of owner window
                   const WCHAR* lpCaption, // address of title of message box
                   UINT uType);            // style of message box
};

extern C__Messages __Messages;
extern C__MessagesW __MessagesW;

/**@name Macros generating messageboxes.
 * if MESSAGES_DEBUG macro is defined, messageboxes display
 * on the first line the file and line where MESSAGExx is in code\\
 *
 */

#ifdef MESSAGES_DEBUG

#ifndef MULTITHREADED_MESSAGES_ENABLE

/** displays messagebox with specified text, not in new thread, distributes message
    of calling thread */
#define MESSAGE(parent, str, buttons) \
    (__Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", __Messages.OStream() << str, \
     __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (__MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

/** displays messagebox with specified text, in new thread, does not distribute message
    of calling thread */
#define MESSAGE_T(str, buttons) \
    (__Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", __Messages.OStream() << str, \
     __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (__MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#else // MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", \
     __Messages.OStream() << str, __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", \
     __MessagesW.OStream() << str, __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << __FILE__ << " " << __LINE__ << ":\n\n", \
     __Messages.OStream() << str, __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << __WFILE__ << L" " << __LINE__ << L":\n\n", \
     __MessagesW.OStream() << str, __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#endif // MULTITHREADED_MESSAGES_ENABLE

#else // MESSAGES_DEBUG

#ifndef MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (__Messages.OStream() << str, __Messages).MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (__MessagesW.OStream() << str, __MessagesW).MessageBox(((parent) == NULL) ? __MessagesParent : (parent), __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (__Messages.OStream() << str, __Messages).MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (__MessagesW.OStream() << str, __MessagesW).MessageBoxT(__MessagesTitleW, (buttons))

#else // MULTITHREADED_MESSAGES_ENABLE

#define MESSAGE(parent, str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << str, \
     __Messages) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), \
                    __MessagesTitle, (buttons))

#define MESSAGEW(parent, str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBox(((parent) == NULL) ? __MessagesParent : (parent), \
                    __MessagesTitleW, (buttons))

#define MESSAGE_T(str, buttons) \
    (EnterMessagesModul(), __Messages.OStream() << str, \
     __Messages) \
        .MessageBoxT(__MessagesTitle, (buttons))

#define MESSAGE_TW(str, buttons) \
    (EnterMessagesModul(), __MessagesW.OStream() << str, \
     __MessagesW) \
        .MessageBoxT(__MessagesTitleW, (buttons))

#endif // MULTITHREADED_MESSAGES_ENABLE

#endif // MESSAGES_DEBUG

/** displays messagebox with specified text and information icon, not in new
    thread, distributes message of calling thread */
#define MESSAGE_I(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONINFORMATION | (buttons))

#define MESSAGE_IW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONINFORMATION | (buttons))

/** displays messagebox with specified text and question icon, not in new
    thread, distributes message of calling thread */
#define MESSAGE_Q(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONQUESTION | (buttons))

#define MESSAGE_QW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONQUESTION | (buttons))

/** displays messagebox with specified text and error icon, not in new
    thread, distributes message of calling thread */
#define MESSAGE_E(parent, str, buttons) \
    MESSAGE(parent, str, MB_ICONEXCLAMATION | (buttons))

#define MESSAGE_EW(parent, str, buttons) \
    MESSAGEW(parent, str, MB_ICONEXCLAMATION | (buttons))

/** displays messagebox with specified text and information icon, in new thread,
    does not distribute message of calling thread */
#define MESSAGE_TI(str, buttons) \
    MESSAGE_T(str, MB_ICONINFORMATION | (buttons))

#define MESSAGE_TIW(str, buttons) \
    MESSAGE_TW(str, MB_ICONINFORMATION | (buttons))

/** displays messagebox with specified text and question icon, in new thread,
    does not distribute message of calling thread */
#define MESSAGE_TQ(str, buttons) \
    MESSAGE_T(str, MB_ICONQUESTION | (buttons))

#define MESSAGE_TQW(str, buttons) \
    MESSAGE_TW(str, MB_ICONQUESTION | (buttons))

/** displays messagebox with specified text and error icon, in new thread,
    does not distribute message of calling thread */
#define MESSAGE_TE(str, buttons) \
    MESSAGE_T(str, MB_ICONEXCLAMATION | (buttons))

#define MESSAGE_TEW(str, buttons) \
    MESSAGE_TW(str, MB_ICONEXCLAMATION | (buttons))

#ifdef MESSAGES_DEBUG

/// MESSAGE_I dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_I(parent, str, buttons) MESSAGE_I(parent, str, (buttons))
#define DMESSAGE_IW(parent, str, buttons) MESSAGE_IW(parent, str, (buttons))

/// MESSAGE_Q dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_Q(parent, str, buttons) MESSAGE_Q(parent, str, (buttons))
#define DMESSAGE_QW(parent, str, buttons) MESSAGE_QW(parent, str, (buttons))

/// MESSAGE_E dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_E(parent, str, buttons) MESSAGE_E(parent, str, (buttons))
#define DMESSAGE_EW(parent, str, buttons) MESSAGE_EW(parent, str, (buttons))

/// MESSAGE_TI dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_TI(str, buttons) MESSAGE_TI(str, (buttons))
#define DMESSAGE_TIW(str, buttons) MESSAGE_TIW(str, (buttons))

/// MESSAGE_TQ dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_TQ(str, buttons) MESSAGE_TQ(str, (buttons))
#define DMESSAGE_TQW(str, buttons) MESSAGE_TQW(str, (buttons))

/// MESSAGE_E dependent on existence of MESSAGES_DEBUG macro
#define DMESSAGE_TE(str, buttons) MESSAGE_TE(str, (buttons))
#define DMESSAGE_TEW(str, buttons) MESSAGE_TEW(str, (buttons))

#else // MESSAGES_DEBUG

// to prevent problems with semicolons in macros defined below
inline int __MessagesEmptyFunction() { return 0; }

#define DMESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#endif // MESSAGES_DEBUG

#else // MESSAGES_DISABLE

// to prevent problems with semicolons in macros defined below
inline int __MessagesEmptyFunction() { return 0; }

#define EnterMessagesModul() __MessagesEmptyFunction()
#define LeaveMessagesModul() __MessagesEmptyFunction()

/* these functions must report compilation error
const char *rsc(int resID);
const WCHAR *rscW(int resID);
const char *spf(const char *formatString, ...);
const WCHAR *spfW(const WCHAR *formatString, ...);
const char *spf(int formatStringResID, ...);
const WCHAR *spfW(int formatStringResID, ...);
const char *err(DWORD error);
const WCHAR *errW(DWORD error);
*/

#define SetMessagesTitle(title) __MessagesEmptyFunction()
#define SetMessagesTitleW(title) __MessagesEmptyFunction()
#define SetMessagesParent(parent) __MessagesEmptyFunction()

#define MESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define MESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#define DMESSAGE_I(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_IW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_Q(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_QW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_E(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_EW(parent, str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TI(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TIW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQ(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TQW(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TE(str, buttons) __MessagesEmptyFunction()
#define DMESSAGE_TEW(str, buttons) __MessagesEmptyFunction()

#endif // MESSAGES_DISABLE

#ifndef UNICODE

#define rscT rsc
#define spfT spf
#define errT err

#define SetMessagesTitleT SetMessagesTitle

#define MESSAGE_IT MESSAGE_I
#define MESSAGE_QT MESSAGE_Q
#define MESSAGE_ET MESSAGE_E
#define MESSAGE_TIT MESSAGE_TI
#define MESSAGE_TQT MESSAGE_TQ
#define MESSAGE_TET MESSAGE_TE

#define DMESSAGE_IT DMESSAGE_I
#define DMESSAGE_QT DMESSAGE_Q
#define DMESSAGE_ET DMESSAGE_E
#define DMESSAGE_TIT DMESSAGE_TI
#define DMESSAGE_TQT DMESSAGE_TQ
#define DMESSAGE_TET DMESSAGE_TE

#else // UNICODE

#define rscT rscW
#define spfT spfW
#define errT errW

#define SetMessagesTitleT SetMessagesTitleW

#define MESSAGE_IT MESSAGE_IW
#define MESSAGE_QT MESSAGE_QW
#define MESSAGE_ET MESSAGE_EW
#define MESSAGE_TIT MESSAGE_TIW
#define MESSAGE_TQT MESSAGE_TQW
#define MESSAGE_TET MESSAGE_TEW

#define DMESSAGE_IT DMESSAGE_IW
#define DMESSAGE_QT DMESSAGE_QW
#define DMESSAGE_ET DMESSAGE_EW
#define DMESSAGE_TIT DMESSAGE_TIW
#define DMESSAGE_TQT DMESSAGE_TQW
#define DMESSAGE_TET DMESSAGE_TEW

#endif // UNICODE
